name: Compile and Deploy Music Sheets

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    # no environment required for pages deployment

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Create Output Directory
        run: mkdir -p _site

      - name: Compile LilyPond Files using Docker
        run: |
          # Find all .ly files recursively and compile them
          # The -o flag redirects the output PDF to the _site directory
          # The output filename is based on the input filename
          find . -name "*.ly" -print0 | while IFS= read -r -d $'\0' file; do
            echo "Compiling: $file"
            docker run --rm \
              -v "$(pwd):/app" \
              lilypond/lilypond:latest \
              /usr/bin/lilypond -o "/app/_site/$(basename "$file" .ly)" "/app/$file"
          done

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4